#!/bin/bash

EASYTRAVEL_VERSION="2.0.0"

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

cd ${BASE}

docker run \
	--rm \
	-it \
	--name easytraveldt \
	-p 8079:8079 \
	-p 8094:8094 \
	dynatrace/easytravel:${EASYTRAVEL_VERSION}

